CREATE TABLE "athlete_applications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"full_name" text NOT NULL,
	"whatsapp" text NOT NULL,
	"email" text NOT NULL,
	"cpf" text NOT NULL,
	"rg" text NOT NULL,
	"birth_date" date NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"nickname" text,
	"position" text NOT NULL,
	"dominant_foot" text NOT NULL,
	"weight_kg" text NOT NULL,
	"height_cm" text NOT NULL,
	"photo_url" text,
	"pix_key" text,
	"contract_start" date,
	"salary_brl" text,
	"rejection_reason" text,
	"reviewed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
