interface AsaasSubscriptionCredentials {
  apiKey: string;
  sandbox?: boolean;
}

export interface CreateSubscriptionInput {
  memberName: string;
  memberEmail: string;
  memberPhone: string;
  cpf: string;
  externalRef: string; // memberId
  planName: string;
  amountCents: number;
}

export interface CreateSubscriptionResult {
  asaasCustomerId: string;
  subscriptionId: string;
  firstPaymentId: string;
  pixQrCode: string;
  pixQrCodeUrl: string;
  nextDueDate: string;
}

export class AsaasSubscriptionClient {
  private baseUrl: string;
  private apiKey: string;

  constructor(credentials: AsaasSubscriptionCredentials) {
    this.apiKey = credentials.apiKey;
    this.baseUrl = credentials.sandbox
      ? "https://sandbox.asaas.com/api/v3"
      : "https://api.asaas.com/v3";
  }

  private async request<T>(path: string, options?: RequestInit): Promise<T> {
    const res = await fetch(`${this.baseUrl}${path}`, {
      ...options,
      headers: {
        "Content-Type": "application/json",
        access_token: this.apiKey,
        ...(options?.headers ?? {}),
      },
    });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(`ASAAS ${res.status} ${path}: ${body}`);
    }
    return res.json() as Promise<T>;
  }

  async createSubscription(input: CreateSubscriptionInput): Promise<CreateSubscriptionResult> {
    // 1. Upsert customer in Asaas
    const customer = await this.request<{ id: string }>("/customers", {
      method: "POST",
      body: JSON.stringify({
        name: input.memberName,
        email: input.memberEmail,
        mobilePhone: input.memberPhone.replace(/\D/g, ""),
        cpfCnpj: input.cpf.replace(/\D/g, ""),
        externalReference: input.externalRef,
      }),
    });

    // 2. Create subscription
    const nextDueDate = new Date().toISOString().split("T")[0];
    const subscription = await this.request<{ id: string; status: string }>("/subscriptions", {
      method: "POST",
      body: JSON.stringify({
        customer: customer.id,
        billingType: "PIX",
        value: input.amountCents / 100,
        nextDueDate,
        cycle: "MONTHLY",
        description: `Sócio-Torcedor — ${input.planName}`,
        externalReference: input.externalRef,
      }),
    });

    // 3. Fetch the first pending payment generated by the subscription
    const paymentsRes = await this.request<{ data: { id: string }[] }>(
      `/subscriptions/${subscription.id}/payments`
    );
    const firstPayment = paymentsRes.data[0];
    if (!firstPayment) {
      throw new Error("Nenhum pagamento gerado pela assinatura");
    }

    // 4. Get PIX QR code for the first payment
    const qr = await this.request<{ payload: string; encodedImage: string }>(
      `/payments/${firstPayment.id}/pixQrCode`
    );

    return {
      asaasCustomerId: customer.id,
      subscriptionId: subscription.id,
      firstPaymentId: firstPayment.id,
      pixQrCode: qr.payload,
      pixQrCodeUrl: `data:image/png;base64,${qr.encodedImage}`,
      nextDueDate,
    };
  }

  async cancelSubscription(subscriptionId: string): Promise<boolean> {
    await this.request(`/subscriptions/${subscriptionId}`, { method: "DELETE" });
    return true;
  }

  async getSubscriptionStatus(subscriptionId: string): Promise<string> {
    const sub = await this.request<{ status: string }>(`/subscriptions/${subscriptionId}`);
    return sub.status;
  }
}

export async function getAsaasSubscriptionClient(): Promise<AsaasSubscriptionClient | null> {
  const { db } = await import("@/lib/db/client");
  const { paymentGateways } = await import("@/lib/db/schema");
  const { eq } = await import("drizzle-orm");
  const { decrypt } = await import("@/lib/payment/encryption");

  const [gw] = await db
    .select()
    .from(paymentGateways)
    .where(eq(paymentGateways.active, true))
    .limit(1);

  if (!gw || !gw.slug.startsWith("asaas")) return null;

  const creds = JSON.parse(decrypt(gw.credentials)) as {
    apiKey: string;
    sandbox?: boolean;
  };

  return new AsaasSubscriptionClient(creds);
}
