import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { db } from "@/lib/db/client";
import { payments, members } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { getActiveGatewayMeta, getActiveGatewayWebhookSecret } from "@/lib/payment";
import { mercadoPagoToPaymentStatus } from "@/lib/payment/mercadopago";
import { applyGatewayStatus } from "@/lib/payment/sync";

function verifySignature(
  secret: string,
  xSignature: string,
  xRequestId: string,
  paymentId: string
): boolean {
  try {
    // x-signature format: ts=1234567890,v1=abc123...
    const parts = Object.fromEntries(
      xSignature.split(",").map((part) => part.split("=") as [string, string])
    );
    const ts = parts["ts"];
    const v1 = parts["v1"];
    if (!ts || !v1) return false;

    const manifest = `id:${paymentId};request-id:${xRequestId};ts:${ts}`;
    const expected = crypto.createHmac("sha256", secret).update(manifest).digest("hex");
    return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(v1));
  } catch {
    return false;
  }
}

async function handleSubscriptionEvent(
  preapprovalId: string,
  accessToken: string
): Promise<void> {
  const res = await fetch(`https://api.mercadopago.com/preapproval/${preapprovalId}`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) return;

  const sub = await res.json() as { status: string; external_reference?: string };
  const memberId = sub.external_reference;
  if (!memberId) return;

  const status = sub.status; // authorized, pending, paused, cancelled
  if (status === "authorized") {
    await db
      .update(members)
      .set({
        status: "active",
        nextBillingDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      })
      .where(eq(members.id, memberId));
  } else if (status === "cancelled" || status === "paused") {
    await db
      .update(members)
      .set({ status: "cancelled", cancelledAt: new Date() })
      .where(eq(members.id, memberId));
  }
}

export async function POST(req: NextRequest): Promise<NextResponse> {
  try {
    const body = await req.json();
    const mpAccessToken = process.env.MP_ACCESS_TOKEN ?? "";

    // Subscription preapproval event
    if (body.type === "subscription_preapproval" && body.data?.id) {
      if (mpAccessToken) {
        await handleSubscriptionEvent(String(body.data.id), mpAccessToken);
      }
      return NextResponse.json({ ok: true });
    }

    // Subscription authorized payment (individual charge inside a subscription)
    if (body.type === "subscription_authorized_payment" && body.data?.id) {
      // The payment was generated by an active subscription → member stays active
      // No additional action needed beyond the initial preapproval event
      return NextResponse.json({ ok: true });
    }

    // Apenas processar eventos de pagamento avulso
    if (body.type !== "payment" || !body.data?.id) {
      return NextResponse.json({ ok: true });
    }

    const mpPaymentId = String(body.data.id);

    // Verificar assinatura HMAC-SHA256 quando webhookSecret estiver configurado
    const [meta, webhookSecret] = await Promise.all([
      getActiveGatewayMeta(),
      getActiveGatewayWebhookSecret(),
    ]);
    if (meta.slug === "mercadopago" && webhookSecret) {
      const xSignature = req.headers.get("x-signature");
      const xRequestId = req.headers.get("x-request-id");
      if (!xSignature || !xRequestId) {
        return NextResponse.json({ error: "Missing signature" }, { status: 401 });
      }
      if (!verifySignature(webhookSecret, xSignature, xRequestId, mpPaymentId)) {
        console.error("[MP webhook] Assinatura inválida — possível spoofing");
        return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
      }
    }

    // Busca o registro de pagamento pelo gateway_payment_id
    const [payment] = await db
      .select()
      .from(payments)
      .where(eq(payments.gatewayPaymentId, mpPaymentId))
      .limit(1);

    if (!payment) {
      console.warn(`[MP webhook] Pagamento ${mpPaymentId} não encontrado no banco`);
      return NextResponse.json({ ok: true });
    }

    // Consultar status atual na API do MP (fonte da verdade)
    if (!mpAccessToken) {
      console.error("[MP webhook] MP_ACCESS_TOKEN não configurado");
      return NextResponse.json({ ok: true });
    }

    const mpRes = await fetch(`https://api.mercadopago.com/v1/payments/${mpPaymentId}`, {
      headers: { Authorization: `Bearer ${mpAccessToken}` },
    });

    if (!mpRes.ok) {
      console.error(`[MP webhook] Falha ao consultar pagamento ${mpPaymentId}`);
      return NextResponse.json({ ok: true });
    }

    const mpPayment = await mpRes.json() as { status: string };
    const newStatus = mercadoPagoToPaymentStatus(mpPayment.status);

    // Aplicação idempotente e direcional: nunca rebaixa um `paid` para `failed`
    // e dispara os efeitos colaterais apenas na transição real.
    await applyGatewayStatus(payment.id, payment.orderId, newStatus);

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("[MP webhook] Erro:", err);
    // Retorna 200 para evitar reenvios
    return NextResponse.json({ ok: true });
  }
}
